rakutentech/ios-sdkutils

.travis.yml, RSDKUtils/KeyStore/KeyStore.swift
I missed changing the KeyStore functions to `public` 😣
=> fix: Change KeyStore functions to 'public'

.xcovignore, Dangerfile, RSDKUtils.xcodeproj/project.pbxproj, RSDKUtils.xcodeproj/xcshareddata/xcschemes/Tests.xcscheme, Sources/RSDKUtilsMain/Networking/Reachability.swift, Tests/TestHost/Info.plist, Tests/Tests/DataExtensionsSpec.swift, Tests/Tests/NSObjectExtensionsSpec.swift, Tests/Tests/ReachabilitySpec.swift, Tests/Tests/URLSessionExtensionsSpec.swift, codecov.yml
Added as much unit tests as it made sense.
Excluded TestHelpers and Nimble submodules source files from code coverage.
=> tests: improve tests coverage

Podfile.lock, RSDKUtils.xcodeproj/project.pbxproj, Tests/Tests/NSObjectExtensionsSpec.swift, Tests/Tests/OptionalExtensionsSpec.swift
It seems like SonarQube has some issues with files that contain `+` character in the name.
Anyway, I ran sonar-scanner locally and I got 80.5% coverage. Fingers crossed.
=> tests: add tests for Optional+Extensions (SDKCF-4826)

Sources/RSDKUtilsMain/Extensions/Bundle+EnvironmentInformation.swift, Sources/RSDKUtilsMain/Extensions/Data+Extensions.swift, Sources/RSDKUtilsMain/Extensions/Optional+CLLocation.swift, Sources/RSDKUtilsMain/Extensions/Optional+Date.swift, Sources/RSDKUtilsMain/Extensions/Optional+String.swift, Sources/RSDKUtilsMain/Extensions/String+Extensions.swift, Tests/Tests/DataExtensionsSpec.swift, Tests/Tests/OptionalExtensionsSpec.swift, Tests/Tests/StringExtensionsSpec.swift
=> feat: SHA256 hexstrings, Wrapped safe hash values, appex (SDKCF-4901)

Podfile, Podfile.lock
fixes build issues after 3.0.0 release
=> fix: fix Podfile ios version

Sources/RSDKUtilsMain/Extensions/UIColor+Extensions.swift, Tests/Tests/UIColorExtensionsSpec.swift
=> feat: add `isRGBAEqual` UIColor extension method

Package.swift, README.md, Sources/RSDKUtilsMain/Extensions/Bundle+EnvironmentInformation.swift, Sources/RSDKUtilsMain/Extensions/NSObject+Extensions.swift, Sources/RSDKUtilsMain/Extensions/Optional+NSObject.swift, Sources/RSDKUtilsMain/Extensions/UIColor+Extensions.swift, Sources/RSDKUtilsMain/Networking/Reachability.swift, Tests/TestHost/AppDelegate.swift, Tests/Tests/NSObjectExtensionsSpec.swift, Tests/Tests/OptionalExtensionsSpec.swift, Tests/Tests/UIColorExtensionsSpec.swift, Tests/Tests/UIViewExtensionSpec.swift
RSDKUtils macOS Support for the macOS PushTester app.
=> feat: RSDKUtils macOS Support (SDKCF-5397)

.github/workflows/test.yml, fastlane/Fastfile
Add GitHub Check with inline test report using [GitHub Actions xcresulttool](https://github.com/marketplace/actions/xcresulttool))
=> ci: GitHub inline test (SDKCF-5616)

.swiftlint.yml, Podfile, Podfile.lock, RSDKUtils.xcodeproj/project.pbxproj, Sources/RSDKUtilsMain/Extensions/UIColor+Extensions.swift, Tests/.swiftlint.yml, Tests/Tests/NSObjectExtensionsSpec.swift
Updated Swiftlint rules basing on the updated [shared template](https://github.com/rakutentech/ios-buildconfig/blob/master/.swiftlint.yml)
=> ci: update Swiftlint rules

Package.swift
Set Quick and Nimble versions range in Package.swift
SDKCF-6742
This PR will solve customer issue with Quick and Nimble.
=> improve: Set Quick and Nimble versions range in Package.swift (SDKCF-6742)

Package.swift, Sources/REventLogger/Extensions/Bundle+AppMetaData.swift, Sources/REventLogger/Extensions/Device+DeviceMetaData.swift, Sources/REventLogger/Utilities/AppInfo.swift, Sources/REventLogger/Utilities/DeviceInfo.swift, Tests/Tests/AppBundleSpec.swift, Tests/Tests/DeviceInfoSpec.swift, Tests/Tests/DeviceMetaDataSpec.swift
[SDKCF-6846][SDKCF-6847]
Retrive APP and Device MetaData
=> feat: Retrieve App and Device MetaData (SDKCF-6846)

CHANGELOG.md, RSDKUtils.xcodeproj/project.pbxproj, Sources/REventLogger/AppLifeCycleListenser.swift, Sources/REventLogger/DependencyManager/DependencyManager.swift, Sources/REventLogger/EventLoggerModule.swift, Sources/REventLogger/REventLogger.swift, Sources/REventLogger/Utilities/Utility.swift, Tests/Tests/REventLogger/AppLifeCycleListenerSpec.swift, Tests/Tests/REventLogger/Helpers/MockServices.swift, Tests/Tests/REventLogger/REventLoggerModuleSpec.swift
Description: Add app lifecycle manager to listen application's active status
=> feat: add app lifecycle listener (SDKCF-6850)

Sources/REventLogger/Networking/REventLoggerSender.swift, Sources/REventLogger/Utilities/TaskSchedulable.swift, Sources/REventLogger/Utilities/Utility.swift, Tests/Tests/REventLogger/REventLoggerSenderSpec.swift
Retry Mechanism that will retry 2 times with interval of 15 seconds and 30 seconds for network errors while pushing events
=> feat: Implement Retry Mechanism

Sample/EventLogger/EventLoggerView.swift
Description:
- Set URLSession error as one of default error
=> improve: add real time error message in the default error (SDKCF-6856)

Sources/REventLogger/EventLoggerModule.swift, Sources/REventLogger/REvent.swift, Sources/REventLogger/REventLoggerEnvironment.swift, Sources/REventLogger/Utilities/Utility.swift, Tests/Tests/REventLogger/Helpers/MockServices.swift, Tests/Tests/REventLogger/REventLoggerModuleSpec.swift, Tests/Tests/REventLogger/REventSpec.swift
=> improve: refactor REvent parameters and log event Logic (SDKCF-6851)

Sample/EventLogger/EventListView.swift, Sample/EventLogger/EventLoggerInteractor.swift, Sample/EventLogger/EventLoggerView.swift
Description:
- Updated SampleApp UI by showing total number of event count in EventList page
- Sorted the list using by firstOccurrance value and sorted dictionary
=> improve: update sample app UI (SDKCF-6856)

Sources/RSDKUtilsMain/Extensions/Bundle+EnvironmentInformation.swift
=> chore: modify device identifier to  Real Time device Name (SDKCF-6880)

Sample/EventLogger/EventLoggerView.swift, Sources/RSDKUtilsMain/Extensions/Bundle+EnvironmentInformation.swift
=> chore: fix crash on sample app on logging event (SDKCF-6882)

Podfile.lock, RSDKUtils.podspec, Sources/Resources/PrivacyInfo.xcprivacy
Description: 
- Add Privacy Manifest File
Ticket:
- SDKCF-6906
=> chore: add PrivacyInfo file (SDKCF-6906)

CHANGELOG.md, Sources/REventLogger/REventLoggerEnvironment.swift, Sources/REventLogger/Utilities/Utility.swift
=> improve: Update App name fetching logic for Eventlogger (SDKCF-6915)

Sources/REventLogger/Networking/REventLoggerSender.swift
=> chore: refactor retry mechanism (SDKCF-6920)

RSDKUtils.podspec
modified s.platforms to remove watchos version
=> chore: update podspec to fix bitrise failure (RMCCX-8306)
